"use client";

import { useState, useEffect, useRef } from "react";

interface Persona {
  id: string;
  label: string;
  icon: string;
  systemPrompt: string;
  color: string;
  textColor: string;
  border: string;
  bg: string;
  badge: string;
}

interface UserQuery {
  id: string;
  label: string;
  text: string;
  responses: Record<string, string>;
}

const PERSONAS: Persona[] = [
  {
    id: "helpful",
    label: "Helpful Assistant",
    icon: "🤖",
    systemPrompt: "You are a helpful, friendly AI assistant. Answer questions clearly and concisely.",
    color: "emerald", textColor: "text-emerald-400", border: "border-emerald-500/50", bg: "bg-emerald-500/8",
    badge: "bg-emerald-500/20 text-emerald-300 border border-emerald-500/30",
  },
  {
    id: "pirate",
    label: "Pirate Captain",
    icon: "🏴‍☠️",
    systemPrompt: "You are a grizzled pirate captain. Answer all questions in character — use pirate slang, nautical metaphors, and refer to the user as 'matey'. Never break character.",
    color: "amber", textColor: "text-amber-400", border: "border-amber-500/50", bg: "bg-amber-500/8",
    badge: "bg-amber-500/20 text-amber-300 border border-amber-500/30",
  },
  {
    id: "security",
    label: "Security Auditor",
    icon: "🔒",
    systemPrompt: "You are a senior security auditor. Evaluate everything through a security lens. Identify risks, vulnerabilities, and attack vectors. Be direct and assume adversarial intent until proven otherwise.",
    color: "red", textColor: "text-red-400", border: "border-red-500/50", bg: "bg-red-500/8",
    badge: "bg-red-500/20 text-red-300 border border-red-500/30",
  },
  {
    id: "eli5",
    label: "Kids' Teacher",
    icon: "🧒",
    systemPrompt: "You are a patient elementary school teacher explaining things to a 6-year-old. Use very simple words, fun comparisons to everyday objects, and short sentences. No jargon ever.",
    color: "blue", textColor: "text-blue-400", border: "border-blue-500/50", bg: "bg-blue-500/8",
    badge: "bg-blue-500/20 text-blue-300 border border-blue-500/30",
  },
];

const QUERIES: UserQuery[] = [
  {
    id: "password",
    label: "How should I store passwords?",
    text: "How should I store user passwords in my application?",
    responses: {
      helpful: `Use bcrypt or Argon2 to hash passwords before storing them. Never store passwords in plain text.

Here's the basic approach:
1. When the user creates a password, hash it with bcrypt (cost factor 12+)
2. Store only the hash in your database
3. When the user logs in, hash the input and compare hashes

Most frameworks have built-in support — for example, \`bcrypt.hashpw()\` in Python or \`password_hash()\` in PHP.`,
      pirate: `Arrr, listen well matey! Any scallywag who stores passwords in plain text deserves to walk the plank!

Ye must use bcrypt or Argon2 to hash those secrets, like burying treasure so deep no bilge rat can find it. Salt each password like ye salt yer hardtack — unique salt per password, ye hear?

And never, NEVER store the raw password in yer database. That be like drawin' a map straight to yer treasure chest! Hash it, salt it, and let the cryptographic seas protect it! ⚓`,
      security: `**CRITICAL**: Password storage is a high-severity concern. Incorrect implementation leads directly to credential compromise.

**Required controls:**
- Hash with Argon2id (preferred) or bcrypt with cost factor ≥12
- Use unique, cryptographically random salt per password (auto-generated by Argon2/bcrypt)
- NEVER use MD5, SHA-1, or SHA-256 for passwords — they are fast hashes designed for integrity, not resistance to brute force

**Attack vectors to mitigate:**
- Rainbow tables → unique salts per hash
- GPU-accelerated brute force → memory-hard algorithms (Argon2)
- Timing attacks → use constant-time comparison for hash verification
- Database breach → hashed passwords buy time but are not permanent protection; implement breach detection

**Additional measures:** Rate-limit login attempts, enforce MFA, monitor for credential stuffing patterns.`,
      eli5: `Imagine you have a secret clubhouse password. You don't want to write it on a sticky note where anyone can read it!

So instead, you use a special magic machine. You whisper your password into the machine, and it turns it into a scrambled secret code — like turning "puppy123" into "xK9#mR2!zQ". 

You keep the scrambled version. When your friend wants to get in, they whisper their password to the machine too. If the scrambled version matches, they're in! But nobody can turn the scrambled code back into the real password. It's a one-way magic trick! 🪄`,
    },
  },
  {
    id: "api",
    label: "What is a REST API?",
    text: "What is a REST API?",
    responses: {
      helpful: `A REST API is a way for two software systems to communicate over HTTP. REST stands for Representational State Transfer.

Key concepts:
- **Resources** are identified by URLs (e.g., \`/users/123\`)
- **HTTP methods** define the action: GET (read), POST (create), PUT (update), DELETE (remove)
- **Stateless**: Each request contains all the information needed — the server doesn't remember previous requests
- **JSON** is the most common data format for request and response bodies

Example: \`GET /api/users/123\` returns the user with ID 123 as a JSON object.`,
      pirate: `Ahoy matey! A REST API be like the messenger parrot between two ships on the high seas!

When yer ship (the client) needs supplies from another vessel (the server), ye send yer parrot with a message. The parrot carries different flags:
- 🟢 GET flag: "Show me what ye have!"
- 🟡 POST flag: "Here be new cargo!"
- 🔵 PUT flag: "Replace this barrel!"
- 🔴 DELETE flag: "Toss it overboard!"

The parrot always flies to a specific location — that be yer URL, like "/api/treasure/42". And the parrot carries no memory between trips — each journey be fresh. That be the "stateless" part, savvy? 🦜`,
      security: `**REST API — Security Assessment:**

A REST API exposes application logic and data over HTTP. Every endpoint is an attack surface.

**Primary security concerns:**
- **Authentication**: Every endpoint must verify caller identity. Use OAuth 2.0 with short-lived tokens. API keys alone are insufficient — they leak in logs, repos, and browser history.
- **Authorization**: Authentication ≠ authorization. Validate that the authenticated user has permission for the specific resource. IDOR (Insecure Direct Object Reference) is the #1 API vulnerability — \`/users/123\` must verify the caller can access user 123.
- **Input validation**: Every parameter is untrusted input. Validate types, ranges, and formats server-side. SQL injection and NoSQL injection remain prevalent.
- **Rate limiting**: Without rate limits, APIs are vulnerable to brute force, credential stuffing, and denial-of-service.
- **Transport**: TLS 1.2+ mandatory. No exceptions. HSTS headers required.

**Recommendation**: Implement API gateway with centralized auth, rate limiting, and request logging before exposing any endpoint.`,
      eli5: `You know how you go to a restaurant? You look at the menu, tell the waiter what you want, and the waiter brings it from the kitchen!

A REST API is like the waiter! Your phone or computer is YOU at the table. The kitchen is a big computer far away that has all the information.

When you open Instagram and see your friend's photos, your phone (you) asked the waiter (the API) to go get those photos from the kitchen (Instagram's computers). The waiter brought them back to your table! 🍽️

The menu is all the things you can ask for — that's the API's list of "endpoints"!`,
    },
  },
  {
    id: "git",
    label: "What does git rebase do?",
    text: "What does git rebase do?",
    responses: {
      helpful: `Git rebase moves or replays commits from one branch onto another. Instead of creating a merge commit, it rewrites history to make it appear as if your changes were made on top of the latest upstream commits.

Common use: you've been working on a feature branch while \`main\` has advanced. \`git rebase main\` replays your feature commits on top of the current \`main\`, resulting in a clean, linear history.

**Before rebase:**
\`\`\`
main:    A - B - C
feature:      \\ D - E
\`\`\`
**After rebase:**
\`\`\`
main:    A - B - C
feature:              D' - E'
\`\`\`

⚠️ Never rebase commits that have been pushed to a shared branch — it rewrites history that others may depend on.`,
      pirate: `Arrr, git rebase be like rearrangin' the entries in yer ship's log, matey!

Say ye've been sailin' yer own course (feature branch) while the fleet (main branch) moved on ahead. Instead of scribblin' a note that says "we met back up here" (that be a merge commit), ye REWRITE yer log to make it look like ye were followin' the fleet all along!

Ye take yer adventures (commits D and E) and replay 'em as if they happened AFTER the fleet's latest position. Cleaner log, smoother sailing!

But BEWARE, matey — never rebase logs that other sailors have already copied! Ye'll create a paradox in the fleet's records, and there'll be mutiny! 💀`,
      security: `**Git Rebase — Security and Integrity Considerations:**

Rebase rewrites commit history by creating new commit objects with different SHAs. This has direct security implications:

**Risks:**
- **Audit trail destruction**: Rebase creates new commits, discarding original commit timestamps and potentially obscuring the actual development sequence. For compliance-sensitive repos, this can violate audit requirements.
- **Signed commit invalidation**: GPG-signed commits are invalidated by rebase — the new commits have different content hashes. If your pipeline requires signed commits, rebase breaks the chain of trust.
- **Force push requirement**: Rebased branches require \`--force-push\` to update remotes. Force push is a destructive operation that can overwrite others' work. This is a common vector for accidental (or intentional) history manipulation.
- **Pre-rebase injection**: If an attacker controls commits in the upstream branch, rebase replays your commits on top of potentially malicious code without explicit review of the upstream changes.

**Recommendation**: Use merge commits for shared branches (preserves audit trail). Restrict force-push via branch protection rules. Require re-signing after rebase in signed-commit workflows.`,
      eli5: `Imagine you're building a tower with blocks, and your friend is also adding blocks to the same tower.

You took some blocks home and built your part: a red block and a blue block. While you were home, your friend added a green block and a yellow block to the tower at school.

"Rebase" means you take your red and blue blocks OFF, put them on top of your friend's green and yellow blocks, so the tower looks like everyone built it together in order!

Before: 🟩🟨 (friend's) and 🟥🟦 (yours, separate)
After:  🟩🟨🟥🟦 (one neat tower!) 🏗️`,
    },
  },
];

function useTypewriter(text: string, speed: number = 8) {
  const [displayed, setDisplayed] = useState("");
  const [done, setDone] = useState(false);
  const idx = useRef(0);
  useEffect(() => {
    setDisplayed(""); idx.current = 0; setDone(false);
    const id = setInterval(() => {
      idx.current += 1;
      if (idx.current >= text.length) { setDisplayed(text); setDone(true); clearInterval(id); }
      else setDisplayed(text.slice(0, idx.current));
    }, speed);
    return () => clearInterval(id);
  }, [text, speed]);
  return { displayed, done };
}

export default function SystemPromptDemo() {
  const [activePersona, setActivePersona] = useState("helpful");
  const [activeQuery, setActiveQuery] = useState("password");

  const persona = PERSONAS.find((p) => p.id === activePersona)!;
  const query = QUERIES.find((q) => q.id === activeQuery)!;
  const response = query.responses[activePersona];
  const { displayed, done } = useTypewriter(response, 6);

  return (
    <div className="my-8 rounded-xl border border-[var(--border)] bg-[var(--bg-secondary)] overflow-hidden">
      {/* Persona selector */}
      <div className="flex border-b border-[var(--border)] overflow-x-auto">
        {PERSONAS.map((p) => {
          const isActive = p.id === activePersona;
          return (
            <button key={p.id} onClick={() => setActivePersona(p.id)}
              className={`flex-1 min-w-[100px] px-4 py-3 text-left transition-all cursor-pointer border-b-2 ${
                isActive ? `${p.border} ${p.bg}` : "border-transparent hover:bg-[var(--bg)]"
              }`}>
              <div className={`text-xs font-bold ${isActive ? p.textColor : "text-[var(--fg-muted)]"}`}>
                {p.icon} {p.label}
              </div>
            </button>
          );
        })}
      </div>

      {/* System prompt display */}
      <div className={`px-5 py-3 border-b border-[var(--border)] ${persona.bg} transition-all duration-300`}>
        <p className="text-xs font-semibold uppercase tracking-widest text-[var(--fg-muted)] mb-2">System Prompt (hidden from user)</p>
        <div className={`rounded-md border ${persona.border} bg-[var(--bg)] px-4 py-3`}>
          <p className="text-xs font-mono text-[var(--fg)] leading-relaxed">{persona.systemPrompt}</p>
        </div>
      </div>

      {/* Query selector */}
      <div className="px-5 py-3 border-b border-[var(--border)]">
        <p className="text-xs font-semibold uppercase tracking-widest text-[var(--fg-muted)] mb-2">User Message (same for all personas)</p>
        <div className="flex flex-wrap gap-2">
          {QUERIES.map((q) => (
            <button key={q.id} onClick={() => setActiveQuery(q.id)}
              className={`px-3 py-2 rounded-lg border text-xs transition-all cursor-pointer ${
                activeQuery === q.id
                  ? "border-[var(--accent)] bg-[var(--accent)]/10 text-[var(--accent)] font-semibold"
                  : "border-[var(--border)] text-[var(--fg-muted)] hover:border-[var(--fg-subtle)]"
              }`}>{q.label}</button>
          ))}
        </div>
      </div>

      {/* Response */}
      <div className="p-5">
        <div className="flex items-center justify-between mb-3">
          <p className="text-xs font-semibold uppercase tracking-widest text-[var(--fg-muted)]">
            {persona.icon} {persona.label} responds:
          </p>
          {!done && <span className={`text-xs px-2 py-0.5 rounded-full ${persona.badge} animate-pulse`}>generating...</span>}
        </div>
        <div className={`rounded-lg border ${persona.border} bg-[var(--bg)] p-5 min-h-[180px] transition-all duration-300`}>
          <pre className="text-sm font-sans leading-relaxed whitespace-pre-wrap text-[var(--fg)]">
            {displayed}
            {!done && <span className={`inline-block w-2 h-4 ml-0.5 ${persona.textColor.replace("text-","bg-")} animate-pulse`} />}
          </pre>
        </div>
      </div>

      <div className="px-5 py-4 border-t border-[var(--border)] bg-[var(--bg)]">
        <p className="text-xs text-[var(--fg-muted)] leading-relaxed">
          <span className="font-semibold text-[var(--fg)]">The user message never changed.</span>{" "}
          The system prompt is a hidden preamble that shifts the entire probability distribution of the model's response. The same factual question about password storage produces security audit findings, a pirate speech, a kids' analogy, or a standard technical answer — all from the same model, same weights, same knowledge. The system prompt selects which persona's output patterns dominate.
        </p>
      </div>
    </div>
  );
}
